from __future__ import annotations

from sqlalchemy.orm import Session

from app.services.sources import ensure_source

PDF_ORIGIN = "pdf-fuentes"
VERIFIED_ON = "2026-04-12"


def _cfg(**kwargs: object) -> dict[str, object]:
    return {"origin": PDF_ORIGIN, **kwargs}


SOURCE_CATALOG: list[dict[str, object]] = [
    {
        "slug": "comprar",
        "name": "COMPR.AR",
        "source_type": "portal",
        "scraping_mode": "coded",
        "connector_slug": "comprar",
        "base_url": "https://comprar.gob.ar",
        "is_active": True,
        "config_json": _cfg(tier="nacional", implemented=True, verified_at=VERIFIED_ON),
    },
    {
        "slug": "contratar",
        "name": "CONTRAT.AR",
        "source_type": "portal",
        "scraping_mode": "api",
        "connector_slug": "contratar",
        "base_url": "https://contratar.gob.ar",
        "is_active": True,
        "config_json": _cfg(
            tier="nacional",
            implemented=True,
            ingestion="csv_oficial",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "boletin-oficial",
        "name": "Boletín Oficial",
        "source_type": "boletin",
        "scraping_mode": "coded",
        "connector_slug": "boletin-oficial",
        "base_url": "https://www.boletinoficial.gob.ar",
        "is_active": True,
        "config_json": _cfg(tier="nacional", implemented=True, verified_at=VERIFIED_ON),
    },
    {
        "slug": "datos-gob-ar",
        "name": "datos.gob.ar",
        "source_type": "portal",
        "scraping_mode": "api",
        "base_url": "https://datos.gob.ar",
        "is_active": False,
        "config_json": _cfg(
            tier="nacional",
            implemented=False,
            worth_pursuing=True,
            notes="dataset complementario; menos prioritario que COMPR.AR y CONTRAT.AR",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "pbac",
        "name": "PBAC",
        "source_type": "portal",
        "scraping_mode": "coded",
        "connector_slug": "pbac",
        "base_url": "https://www.pbac.cgp.gba.gov.ar",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="Buenos Aires",
            implemented=True,
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-caba",
        "name": "GCBA",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://buenosaires.gob.ar/haciendayfinanzas/consulta-de-compras-y-contrataciones",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="CABA",
            implemented=False,
            worth_pursuing=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-cordoba",
        "name": "Provincia de Córdoba",
        "source_type": "portal",
        "scraping_mode": "api",
        "connector_slug": "licitaciones-cordoba",
        "base_url": "https://compras.cordoba.gob.ar/",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="Córdoba",
            implemented=True,
            worth_pursuing=True,
            access="web_public",
            notes="usa apifg/compra/compra para el listado público activo y apifg/compra/compra/proveedor/{id} para detalle",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-santa-fe",
        "name": "Provincia de Santa Fe",
        "source_type": "portal",
        "scraping_mode": "json",
        "connector_slug": "licitaciones-santa-fe",
        "base_url": "https://www.santafe.gov.ar/gestionesdecompras/site/index.php?a=consultas.index",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="Santa Fe",
            implemented=True,
            worth_pursuing=True,
            access="web_public",
            notes="usa endpoint Ajax oficial del portal de gestiones de compras",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-mendoza",
        "name": "Provincia de Mendoza",
        "source_type": "portal",
        "scraping_mode": "html",
        "connector_slug": "licitaciones-mendoza",
        "base_url": "https://comprar.mendoza.gov.ar/",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="Mendoza",
            implemented=True,
            worth_pursuing=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-tucuman",
        "name": "Provincia de Tucumán",
        "source_type": "portal",
        "scraping_mode": "html",
        "connector_slug": "licitaciones-tucuman",
        "base_url": "https://compras.tucuman.gob.ar/",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="Tucumán",
            implemented=True,
            worth_pursuing=True,
            access="web_public",
            notes="usa ver_llamados_compras_avanzado.php?estado_compra=1 y pagina_actual para recorrer convocatorias abiertas",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-entre-rios",
        "name": "Provincia de Entre Ríos",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.entrerios.gov.ar/compras/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="Entre Ríos",
            implemented=False,
            access="web_public",
        ),
    },
    {
        "slug": "licitaciones-salta",
        "name": "Provincia de Salta",
        "source_type": "portal",
        "scraping_mode": "html",
        "connector_slug": "licitaciones-salta",
        "base_url": "https://compras.salta.gob.ar/",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="Salta",
            implemented=True,
            worth_pursuing=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-misiones",
        "name": "Provincia de Misiones",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.cg.misiones.gov.ar/proveedores/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="Misiones",
            implemented=False,
            access="web_public",
            notes="portal de proveedores confirmado; falta validar si expone licitaciones activas reutilizables",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-chaco",
        "name": "Provincia del Chaco",
        "source_type": "portal",
        "scraping_mode": "html",
        "connector_slug": "licitaciones-chaco",
        "base_url": "https://compras.chaco.gob.ar/",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="Chaco",
            implemented=True,
            worth_pursuing=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-corrientes",
        "name": "Provincia de Corrientes",
        "source_type": "portal",
        "scraping_mode": "api",
        "connector_slug": "licitaciones-corrientes",
        "base_url": "https://www.cgpcorrientes.gov.ar/licitaciones-component",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="Corrientes",
            implemented=True,
            access="web_public",
            notes="usa https://nportal.cgpc.gob.ar/documentos/apiweb/generic?novedad=true; se filtran licitaciones y se excluyen pliegos para evitar duplicados",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-santiago-del-estero",
        "name": "Provincia de Santiago del Estero",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.sde.gov.ar/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="Santiago del Estero",
            implemented=False,
            worth_pursuing=False,
            access="referencia_oficial",
            notes="aparece en el mapa PDF y en directorio oficial de Santa Fe, pero falta portal público estable",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-san-juan",
        "name": "Provincia de San Juan",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.sanjuan.gov.ar/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="San Juan",
            implemented=False,
            access="web_public",
            notes="falta confirmar endpoint específico de compras",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-jujuy",
        "name": "Provincia de Jujuy",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.jujuy.gob.ar/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="Jujuy",
            implemented=False,
            worth_pursuing=False,
            access="referencia_oficial",
            notes="mencionada en el PDF; falta portal público de compras claramente identificable",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-rio-negro",
        "name": "Provincia de Río Negro",
        "source_type": "portal",
        "scraping_mode": "html",
        "connector_slug": "licitaciones-rio-negro",
        "base_url": "https://compras.rionegro.gov.ar/",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="Río Negro",
            implemented=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-neuquen",
        "name": "Provincia del Neuquén",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.neuquen.gov.ar/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="Neuquén",
            implemented=False,
            access="web_public",
            notes="CODINEU citado en el PDF; falta validar endpoint definitivo del portal",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-formosa",
        "name": "Provincia de Formosa",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.formosa.gob.ar/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="Formosa",
            implemented=False,
            worth_pursuing=False,
            access="referencia_oficial",
            notes="mencionada en el PDF; sin endpoint público claro para scraping",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-chubut",
        "name": "Provincia del Chubut",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.chubut.gov.ar/",
        "is_active": False,
        "config_json": _cfg(tier="provincial", province="Chubut", implemented=False),
    },
    {
        "slug": "licitaciones-san-luis",
        "name": "Provincia de San Luis",
        "source_type": "portal",
        "scraping_mode": "html",
        "connector_slug": "licitaciones-san-luis",
        "base_url": "https://www.sistemacompras.sanluis.gov.ar/",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="San Luis",
            implemented=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-catamarca",
        "name": "Provincia de Catamarca",
        "source_type": "portal",
        "scraping_mode": "html",
        "connector_slug": "licitaciones-catamarca",
        "base_url": "https://www.cgp-catamarca.gob.ar/contrataciones.php",
        "is_active": True,
        "config_json": _cfg(
            tier="provincial",
            province="Catamarca",
            implemented=True,
            worth_pursuing=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-la-rioja",
        "name": "Provincia de La Rioja",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://compras.larioja.gov.ar/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="La Rioja",
            implemented=False,
            worth_pursuing=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "licitaciones-la-pampa",
        "name": "Provincia de La Pampa",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.lapampa.gob.ar/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="La Pampa",
            implemented=False,
        ),
    },
    {
        "slug": "licitaciones-santa-cruz",
        "name": "Provincia de Santa Cruz",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.santacruz.gob.ar/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="Santa Cruz",
            implemented=False,
        ),
    },
    {
        "slug": "licitaciones-tierra-del-fuego",
        "name": "Provincia de Tierra del Fuego",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://compras.tierradelfuego.gov.ar/",
        "is_active": False,
        "config_json": _cfg(
            tier="provincial",
            province="Tierra del Fuego",
            implemented=False,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "ypf",
        "name": "YPF",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.ypf.com",
        "is_active": False,
        "config_json": _cfg(
            tier="empresa-estado",
            implemented=False,
            worth_pursuing=False,
            access="login_required",
            notes="portal de proveedores; alto costo operativo para el estado actual del producto",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "aysa",
        "name": "AySA",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.aysa.com.ar",
        "is_active": False,
        "config_json": _cfg(
            tier="empresa-estado",
            implemented=False,
            access="web_public",
        ),
    },
    {
        "slug": "arsat",
        "name": "ARSAT",
        "source_type": "portal",
        "scraping_mode": "html",
        "connector_slug": "arsat",
        "base_url": "https://www.arsat.com.ar/acerca-de-arsat/transparencia-activa/compras-y-contrataciones/",
        "is_active": True,
        "config_json": _cfg(
            tier="empresa-estado",
            implemented=True,
            worth_pursuing=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "trenes-argentinos",
        "name": "Trenes Argentinos",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.argentina.gob.ar/transporte/trenes-argentinos",
        "is_active": False,
        "config_json": _cfg(
            tier="empresa-estado",
            implemented=False,
            worth_pursuing=False,
            notes="alta superposición con COMPR.AR y sitios ferroviarios satélite",
        ),
    },
    {
        "slug": "correo-argentino",
        "name": "Correo Argentino",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.correoargentino.com.ar",
        "is_active": False,
        "config_json": _cfg(tier="empresa-estado", implemented=False),
    },
    {
        "slug": "aerolineas-argentinas",
        "name": "Aerolíneas Argentinas",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.aerolineas.com.ar",
        "is_active": False,
        "config_json": _cfg(tier="empresa-estado", implemented=False),
    },
    {
        "slug": "invap",
        "name": "INVAP",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.invap.com.ar",
        "is_active": False,
        "config_json": _cfg(tier="empresa-estado", implemented=False),
    },
    {
        "slug": "nasa-nucleoelectrica",
        "name": "Nucleoeléctrica",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.na-sa.com.ar",
        "is_active": False,
        "config_json": _cfg(tier="empresa-estado", implemented=False),
    },
    {
        "slug": "adif",
        "name": "ADIF",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.argentina.gob.ar/transporte/trenes-argentinos-infraestructura",
        "is_active": False,
        "config_json": _cfg(
            tier="empresa-estado",
            implemented=False,
            worth_pursuing=False,
            notes="vale más integrar ADIF/Trenes por familia ferroviaria si aparecen gaps reales",
        ),
    },
    {
        "slug": "banco-nacion",
        "name": "Banco Nación",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.bna.com.ar",
        "is_active": False,
        "config_json": _cfg(tier="empresa-estado", implemented=False),
    },
    {
        "slug": "bice",
        "name": "BICE",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.bice.com.ar",
        "is_active": False,
        "config_json": _cfg(tier="empresa-estado", implemented=False),
    },
    {
        "slug": "vialidad-nacional",
        "name": "Vialidad Nacional",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.argentina.gob.ar/obras-publicas/vialidad-nacional",
        "is_active": False,
        "config_json": _cfg(
            tier="empresa-estado",
            implemented=False,
            worth_pursuing=False,
            notes="el PDF ya indica que la publicación fuerte corre por CONTRAT.AR",
        ),
    },
    {
        "slug": "universidades-nacionales",
        "name": "Universidades Nacionales",
        "source_type": "manual",
        "scraping_mode": "hybrid",
        "base_url": "https://www.argentina.gob.ar/educacion/universidades",
        "is_active": False,
        "config_json": _cfg(
            tier="descentralizado",
            group="57 universidades",
            implemented=False,
            worth_pursuing=False,
            notes="alto valor total, pero mala relación costo/beneficio como fuente agregada única",
        ),
    },
    {
        "slug": "pami",
        "name": "PAMI",
        "source_type": "portal",
        "scraping_mode": "html",
        "connector_slug": "pami",
        "base_url": "https://transparenciaactiva.pami.org.ar/compras-y-contrataciones/",
        "is_active": True,
        "config_json": _cfg(
            tier="descentralizado",
            implemented=True,
            worth_pursuing=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "superintendencia-salud",
        "name": "SSSalud",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.argentina.gob.ar/sssalud",
        "is_active": False,
        "config_json": _cfg(tier="descentralizado", implemented=False),
    },
    {
        "slug": "anmat",
        "name": "ANMAT",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.argentina.gob.ar/anmat",
        "is_active": False,
        "config_json": _cfg(
            tier="descentralizado",
            implemented=False,
            worth_pursuing=False,
            notes="potable, pero detrás de PAMI y provincias por volumen esperado",
        ),
    },
    {
        "slug": "conicet",
        "name": "CONICET",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.conicet.gov.ar",
        "is_active": False,
        "config_json": _cfg(
            tier="descentralizado",
            implemented=False,
            worth_pursuing=False,
            notes="mucho gasto de integración para volumen acotado y alta superposición con COMPR.AR",
        ),
    },
    {
        "slug": "inti",
        "name": "INTI",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.inti.gob.ar",
        "is_active": False,
        "config_json": _cfg(tier="descentralizado", implemented=False),
    },
    {
        "slug": "inta",
        "name": "INTA",
        "source_type": "portal",
        "scraping_mode": "api",
        "connector_slug": "inta",
        "base_url": "https://compras.inta.gob.ar/",
        "is_active": True,
        "config_json": _cfg(
            tier="descentralizado",
            implemented=True,
            worth_pursuing=True,
            access="web_public",
            verified_at=VERIFIED_ON,
        ),
    },
    {
        "slug": "cnea",
        "name": "CNEA",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.argentina.gob.ar/cnea",
        "is_active": False,
        "config_json": _cfg(tier="descentralizado", implemented=False),
    },
    {
        "slug": "conae",
        "name": "CONAE",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.argentina.gob.ar/ciencia/conae",
        "is_active": False,
        "config_json": _cfg(tier="descentralizado", implemented=False),
    },
    {
        "slug": "anses",
        "name": "ANSES",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.anses.gob.ar",
        "is_active": False,
        "config_json": _cfg(
            tier="descentralizado",
            implemented=False,
            worth_pursuing=False,
            notes="alto volumen potencial, pero muchas publicaciones relevantes ya aparecen en COMPR.AR",
        ),
    },
    {
        "slug": "arca-afip",
        "name": "ARCA / AFIP",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.afip.gob.ar",
        "is_active": False,
        "config_json": _cfg(
            tier="descentralizado",
            implemented=False,
            worth_pursuing=False,
            notes="vigilar sólo si aparecen gaps persistentes respecto de COMPR.AR",
        ),
    },
    {
        "slug": "senasa",
        "name": "SENASA",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.argentina.gob.ar/senasa",
        "is_active": False,
        "config_json": _cfg(tier="descentralizado", implemented=False),
    },
    {
        "slug": "parques-nacionales",
        "name": "Parques Nacionales",
        "source_type": "portal",
        "scraping_mode": "html",
        "base_url": "https://www.argentina.gob.ar/parquesnacionales",
        "is_active": False,
        "config_json": _cfg(tier="descentralizado", implemented=False),
    },
]


def seed_source_catalog(db: Session) -> None:
    for spec in SOURCE_CATALOG:
        ensure_source(db, **spec)
    db.flush()
